"""buat table user

Revision ID: 280fe14ef365
Revises: 
Create Date: 2023-03-05 00:11:01.031229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280fe14ef365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('identity_number', sa.BigInteger(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
