"""change vector datatype

Revision ID: 414ac770bc3e
Revises: a28dc5c2d857
Create Date: 2023-03-05 02:07:42.707209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '414ac770bc3e'
down_revision = 'a28dc5c2d857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('vector',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=7500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('vector',
               existing_type=sa.String(length=7500),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
