"""revisi column vector dan identity_number

Revision ID: a28dc5c2d857
Revises: 280fe14ef365
Create Date: 2023-03-05 00:31:32.241324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28dc5c2d857'
down_revision = '280fe14ef365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['identity_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('vector')

    # ### end Alembic commands ###
